# Generated by Django 3.2.7 on 2022-10-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.AddField(
            model_name='room',
            name='birthday',
            field=models.CharField(default=True, max_length=45),
        ),
        migrations.AddField(
            model_name='room',
            name='pressured',
            field=models.IntegerField(db_column='pressureD', default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='pressures',
            field=models.IntegerField(db_column='pressureS', default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='sex',
            field=models.CharField(default=True, max_length=45),
        ),
        migrations.AddField(
            model_name='room',
            name='temperature',
            field=models.FloatField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='weight',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
