# Generated by Django 3.2.7 on 2022-10-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20221024_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Data',
        ),
    ]
