# Generated by Django 3.2.7 on 2022-10-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_data_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='created',
        ),
        migrations.RemoveField(
            model_name='data',
            name='updated',
        ),
        migrations.AddField(
            model_name='data',
            name='image_id',
            field=models.CharField(default=True, max_length=45),
        ),
    ]
