# Generated by Django 3.2.7 on 2022-11-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20221025_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image_id',
            field=models.IntegerField(db_column='imageid', default=True),
        ),
    ]
