# Generated by Django 3.2.7 on 2022-11-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_data_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image_id',
            field=models.IntegerField(db_column='imageid'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pressured',
            field=models.IntegerField(db_column='pressureD'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pressures',
            field=models.IntegerField(db_column='pressureS'),
        ),
    ]
