# Generated by Django 3.2.7 on 2022-12-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20221130_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField(db_column='imageid')),
                ('name', models.CharField(max_length=45)),
                ('birthday', models.CharField(default=True, max_length=45)),
                ('sex', models.CharField(default=True, max_length=45)),
                ('weight', models.FloatField(default=True)),
                ('height', models.FloatField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='data',
            name='height',
        ),
        migrations.RemoveField(
            model_name='data',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='data',
            name='weight',
        ),
    ]
