# Generated by Django 3.2.7 on 2022-12-08 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20221208_1001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Data1',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
