# Generated by Django 3.2.7 on 2022-12-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20221208_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='data1',
            name='name',
            field=models.CharField(default=True, max_length=45),
        ),
    ]
