# Generated by Django 3.2.7 on 2022-12-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20221209_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data1',
            name='userid',
        ),
        migrations.AddField(
            model_name='data1',
            name='name',
            field=models.CharField(default=True, max_length=45),
        ),
    ]
