# Generated by Django 3.2.7 on 2022-12-15 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20221210_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data1',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user1'),
        ),
    ]
