# Generated by Django 3.2.7 on 2022-12-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_data1_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data1',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
