# Generated by Django 3.2.7 on 2022-12-15 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_data1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='data1',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.user1'),
            preserve_default=False,
        ),
    ]
