# Generated by Django 3.2.7 on 2022-12-15 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_data1_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data1',
            name='user',
        ),
    ]
