# Generated by Django 3.2.7 on 2022-12-15 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_data1_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('weight', models.FloatField(default=True)),
                ('temperature', models.FloatField(default=True)),
                ('pressures', models.IntegerField(db_column='pressureS')),
                ('pressured', models.IntegerField(db_column='pressureD')),
            ],
        ),
        migrations.DeleteModel(
            name='Data1',
        ),
        migrations.RenameModel(
            old_name='User1',
            new_name='User2',
        ),
        migrations.AddField(
            model_name='data2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user2'),
        ),
    ]
