# Generated by Django 3.2.7 on 2022-12-15 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20221215_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data2',
            name='name',
        ),
        migrations.RemoveField(
            model_name='data2',
            name='user',
        ),
    ]
