# Generated by Django 3.2.7 on 2022-12-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20221215_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('weight', models.FloatField(default=True)),
                ('temperature', models.FloatField(default=True)),
                ('pressures', models.IntegerField(db_column='pressureS')),
                ('pressured', models.IntegerField(db_column='pressureD')),
            ],
        ),
        migrations.CreateModel(
            name='User0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField(db_column='imageid')),
                ('name', models.CharField(max_length=45)),
                ('birthday', models.CharField(default=True, max_length=45)),
                ('sex', models.CharField(default=True, max_length=45)),
                ('height', models.FloatField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Data2',
        ),
        migrations.DeleteModel(
            name='User2',
        ),
    ]
