# Generated by Django 3.2.7 on 2022-12-15 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20221215_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='data0',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='base.user0'),
        ),
    ]
