# Generated by Django 3.2.7 on 2022-12-15 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_data0_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data0',
            name='user',
        ),
        migrations.AlterField(
            model_name='data0',
            name='name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='base.user0'),
        ),
    ]
