# Generated by Django 3.2.7 on 2022-12-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_data0_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data0',
            name='name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='base.user0'),
        ),
    ]
