# Generated by Django 3.2.7 on 2022-12-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_data0_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=True)),
                ('temperature', models.FloatField(default=True)),
                ('pressures', models.IntegerField(db_column='pressureS')),
                ('pressured', models.IntegerField(db_column='pressureD')),
            ],
        ),
        migrations.CreateModel(
            name='User5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField(db_column='imageid')),
                ('name', models.CharField(max_length=45)),
                ('birthday', models.CharField(default=True, max_length=45)),
                ('sex', models.CharField(default=True, max_length=45)),
                ('height', models.FloatField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Data0',
        ),
        migrations.DeleteModel(
            name='User0',
        ),
        migrations.AddField(
            model_name='data5',
            name='name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='base.user5'),
        ),
    ]
