# Generated by Django 3.2.7 on 2022-12-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='data6',
            name='z',
            field=models.IntegerField(default=0),
        ),
    ]
