# Generated by Django 3.2.7 on 2022-12-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_data6_z'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data6',
            old_name='z',
            new_name='bmi',
        ),
    ]
