# Generated by Django 3.2.7 on 2022-12-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_rename_z_data6_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data6',
            name='bmi',
            field=models.FloatField(default=0),
        ),
    ]
