# Generated by Django 3.2.7 on 2022-12-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20221229_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='bmi',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
