# Generated by Django 3.2.7 on 2022-12-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20221229_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data6',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='test',
            name='x',
            field=models.FloatField(default=170),
        ),
        migrations.AlterField(
            model_name='test',
            name='y',
            field=models.FloatField(default=55),
        ),
    ]
