# Generated by Django 3.2.7 on 2022-12-29 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20221229_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='data6',
            name='names',
            field=models.CharField(default=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='data6',
            name='name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='base.user6'),
        ),
    ]
