# Generated by Django 3.2.7 on 2022-12-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20221229_2013'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data6',
            table='tb_data',
        ),
        migrations.AlterModelTable(
            name='user6',
            table='tb_user',
        ),
    ]
