# Generated by Django 3.2.7 on 2022-12-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20221229_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data6',
            name='names',
        ),
    ]
