# Generated by Django 3.2.7 on 2022-12-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_rename_name_data6_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='x',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='test',
            name='y',
            field=models.FloatField(default=2.0),
        ),
    ]
