# Generated by Django 3.2.7 on 2022-12-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20221229_2318'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data6',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user6',
            table=None,
        ),
    ]
