# Generated by Django 3.2.7 on 2022-12-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20221230_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='data6',
            name='result',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='data6',
            name='pressured',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='data6',
            name='pressures',
            field=models.IntegerField(default=True),
        ),
    ]
