# Generated by Django 3.2.7 on 2022-12-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_data6_bmr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data6',
            name='result1',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='data6',
            name='result2',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='data6',
            name='result3',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='user6',
            name='birthday',
            field=models.CharField(default=False, max_length=45),
        ),
        migrations.AlterField(
            model_name='user6',
            name='height',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='user6',
            name='sex',
            field=models.CharField(default=False, max_length=45),
        ),
    ]
