# Generated by Django 3.2.7 on 2022-12-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20221231_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
