# Generated by Django 3.2.7 on 2022-12-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
