# Generated by Django 3.2.7 on 2022-12-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_alter_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data6',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
