# Generated by Django 3.2.7 on 2022-12-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_data6_updatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data6',
            name='updatetime',
            field=models.DateField(auto_now=True),
        ),
    ]
