# Generated by Django 3.2.7 on 2022-12-31 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_data6_updatetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='date',
            new_name='udate',
        ),
        migrations.AddField(
            model_name='test',
            name='cdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
