# Generated by Django 3.2.7 on 2022-12-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_auto_20221231_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='udate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
