# Generated by Django 3.2.7 on 2022-12-31 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_auto_20221231_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='data6',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 31, 12, 5, 53, 322830, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
