# Generated by Django 3.2.7 on 2022-12-31 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_data6_createtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user6',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 31, 12, 7, 3, 144848, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user6',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
