# Generated by Django 3.2.7 on 2022-12-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_auto_20221231_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data6',
            name='createtime',
        ),
        migrations.RemoveField(
            model_name='user6',
            name='createtime',
        ),
        migrations.RemoveField(
            model_name='user6',
            name='updatetime',
        ),
    ]
