# Generated by Django 3.2.7 on 2022-12-31 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auto_20221231_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='data7',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 31, 12, 23, 41, 944267, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user7',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 31, 12, 24, 2, 169975, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user7',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
