# Generated by Django 3.2.7 on 2023-01-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_auto_20221231_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data6',
            name='result2',
        ),
        migrations.RemoveField(
            model_name='data6',
            name='result3',
        ),
    ]
