# Generated by Django 3.2.7 on 2023-01-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_auto_20230102_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='data6',
            name='heartbeat',
            field=models.IntegerField(default=0),
        ),
    ]
