# Generated by Django 3.2.7 on 2023-01-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_data6_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='data6',
            name='result2',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='data6',
            name='result3',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='data6',
            name='result4',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
