# Generated by Django 3.2.7 on 2023-01-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_auto_20230102_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data6',
            name='updatetime',
        ),
        migrations.RemoveField(
            model_name='user6',
            name='updatetime',
        ),
    ]
