# Generated by Django 3.2.7 on 2023-03-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='userid',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='base.user6'),
        ),
    ]
