# Generated by Django 3.2.7 on 2023-03-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_medicine_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='userid',
            new_name='user',
        ),
    ]
