# Generated by Django 3.2.7 on 2023-03-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_rename_userid_medicine_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='user',
            new_name='userid',
        ),
    ]
