# Generated by Django 3.2.7 on 2023-05-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_auto_20230517_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=100)),
                ('sname', models.CharField(default=True, max_length=100)),
                ('indications', models.CharField(default=True, max_length=100)),
                ('side_effect', models.CharField(default=True, max_length=100)),
            ],
        ),
    ]
