# Generated by Django 3.2.7 on 2023-05-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_m'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M',
        ),
        migrations.AddField(
            model_name='medicine',
            name='hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='min',
            field=models.IntegerField(null=True),
        ),
    ]
