# Generated by Django 3.2.7 on 2023-05-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_auto_20230517_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='hour',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='min',
            field=models.TextField(null=True),
        ),
    ]
